name: Build

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Clone JP-BundlesPNG JP branch
        run: |
          git clone --depth 1 --branch JP git@github.com:bluearchive-cafe/JP-BundlesPNG.git output

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python deps
        run: pip install requests tqdm

      - name: Prepare Tool Environment
        run: |
          git clone --depth 1 git@github.com:beichen23333/BlueArchive-Translation.git tool
          cp -r tool/* . && rm -rf tool

      - name: Download info
        run: |
          curl -sL -o info_jp.json https://raw.githubusercontent.com/bluearchive-cafe/BA-Translation/refs/heads/main/info_jp.json

      - name: AssetStudio permission
        run: chmod +x AssetStudio/AssetStudioModCLI

      - name: Update bundle
        run: |
          chmod +x update/update_bundle.sh
          update/update_bundle.sh JP

      - name: Run bundle extractor
        run: python extract.py

      - name: Commit and Push to JP branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          cd output

          git checkout JP

          count=0
          batch=""

          for dir in */; do
            echo "Queue folder: $dir"
            batch="$batch $dir"
            count=$((count+1))

            if [ $count -eq 3 ]; then
              echo "Committing batch:$batch"
              git add $batch

              git diff --cached --quiet || git commit -m "Update JP bundle PNGs batch"
              git push origin JP || exit 1

              count=0
              batch=""
              git reset
            fi
          done

          if [ -n "$batch" ]; then
            echo "Committing final batch:$batch"
            git add $batch
            git diff --cached --quiet || git commit -m "Update JP bundle PNGs final batch"
            git push origin JP || exit 1
            git reset
          fi
