name: Build

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Clone JP-BundlesPNG repo
        run: |
          git clone --depth 1 git@github.com:bluearchive-cafe/JP-BundlesPNG.git output

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python deps
        run: pip install requests tqdm

      - name: Prepare Tool Environment
        run: |
          git clone --depth 1 git@github.com:beichen23333/BlueArchive-Translation.git tool
          cp -r tool/* . && rm -rf tool

      - name: Download info
        run: |
          curl -sL -o info_jp.json https://raw.githubusercontent.com/bluearchive-cafe/BA-Translation/refs/heads/main/info_jp.json

      - name: AssetStudio permission
        run: chmod +x AssetStudio/AssetStudioModCLI

      - name: Update bundle
        run: |
          chmod +x update/update_bundle.sh
          update/update_bundle.sh JP

      - name: Run bundle extractor
        run: python extract.py

      - name: Commit and Push Results
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          cd output
          git add .
          git commit -m "Update JP bundle PNGs" || exit 0
          git push

